on:
  push:
    branches:
      - master
      - beta
      - develop
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-*'

name: ci-build

permissions:
  contents: write

jobs:
  build:
    name: Build Release Assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5

      - name: Build for Windows
        env:
          GOOS: windows
          GOARCH: amd64
        run: go build -o app-win.exe

      - name: Build for Linux
        env:
          GOOS: linux
          GOARCH: amd64
        run: go build -o app-linux

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-builds
          path: |
            app-win.exe
            app-linux