on:
  push:
    branches:
      - master
      - beta
      - develop
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-*'

name: ci-build

permissions:
  contents: write

jobs:
  build:
    name: Build Release Assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e  # v7.0.0

      - name: Build for Windows
        env:
          GOOS: windows
          GOARCH: amd64
        run: go build -o app-win.exe

      - name: Build for Linux
        env:
          GOOS: linux
          GOARCH: amd64
        run: go build -o app-linux

      - name: Upload build artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          name: app-builds
          path: |
            app-win.exe
            app-linux